"ui.background" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.virtual.jump-label" = { fg = "base05", modifiers = ["bold", "underlined"] }
"ui.virtual.ruler" = { bg = "base01" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"comment" = { fg = "base03", modifiers = ["italic"] }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.text" = "base05"
"operator" = "base05"
"ui.text.focus" = "base05"
"variable" = "base05"
"constant.numeric" = "base05"
"constant" = "base05"
"attribute" = "base05"
"type" = "base05"
"ui.cursor.match" = { fg = "base05", modifiers = ["underlined"] }
"string"  = "base05"
"variable.other.member" = "base05"
"constant.character.escape" = "base05"
"function" = "base05"
"constructor" = "base05"
"special" = "base05"
"keyword" = { fg = "base05", modifiers = ["bold"] }
"label" = "base05"
"namespace" = "base05"
"ui.help" = { fg = "base05", bg = "base01" }

"markup.heading" = "base05"
"markup.list" = "base05"
"markup.bold" = { fg = "base05", modifiers = ["bold"] }
"markup.italic" = { fg = "base05", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base05", modifiers = ["underlined"] }
"markup.link.text" = "base05"
"markup.quote" = "base05"
"markup.raw" = "base05"

"diff.plus" = "base05"
"diff.delta" = "base05"
"diff.minus" = "base05"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base05"
"hint" = "base03"
"debug" = "base03"
"warning" = "base05"
"error" = "base05"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base05", bg = "base01" }

[palette]
base00 = "#FFFFFF" # Default Background (белый)
base01 = "#FFFFFF" # Lighter Background (белый)
base02 = "#DDDDDD" # Selection Background (светло-серый)
base03 = "#888888" # Comments (серый)
base04 = "#666666" # Dark Foreground (серый для статусбара)
base05 = "#666666" # Default Foreground (серый как в статус баре)
base06 = "#666666" # Light Foreground (серый)
base07 = "#FFFFFF" # Light Background (белый)
base08 = "#666666" # Variables (серый)
base09 = "#666666" # Integers (серый)
base0A = "#666666" # Classes (серый)
base0B = "#666666" # Strings (серый)
base0C = "#666666" # Support (серый)
base0D = "#666666" # Functions (серый)
base0E = "#666666" # Keywords (серый)
base0F = "#666666" # Deprecated (серый)
